/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout.chat.index'
import { Route as LayoutChatIdIndexRouteImport } from './routes/_layout.chat.$id.index'
import { Route as LayoutChatIdExportRouteImport } from './routes/_layout.chat.$id.export'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatIdIndexRoute = LayoutChatIdIndexRouteImport.update({
  id: '/chat/$id/',
  path: '/chat/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatIdExportRoute = LayoutChatIdExportRouteImport.update({
  id: '/chat/$id/export',
  path: '/chat/$id/export',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/chat/$id/export': typeof LayoutChatIdExportRoute
  '/chat/$id': typeof LayoutChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/chat/$id/export': typeof LayoutChatIdExportRoute
  '/chat/$id': typeof LayoutChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/chat/$id/export': typeof LayoutChatIdExportRoute
  '/_layout/chat/$id/': typeof LayoutChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/settings'
    | '/'
    | '/chat'
    | '/chat/$id/export'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/settings'
    | '/'
    | '/chat'
    | '/chat/$id/export'
    | '/chat/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/chat/'
    | '/_layout/chat/$id/export'
    | '/_layout/chat/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/$id/': {
      id: '/_layout/chat/$id/'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof LayoutChatIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/$id/export': {
      id: '/_layout/chat/$id/export'
      path: '/chat/$id/export'
      fullPath: '/chat/$id/export'
      preLoaderRoute: typeof LayoutChatIdExportRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
  LayoutChatIdExportRoute: typeof LayoutChatIdExportRoute
  LayoutChatIdIndexRoute: typeof LayoutChatIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
  LayoutChatIdExportRoute: LayoutChatIdExportRoute,
  LayoutChatIdIndexRoute: LayoutChatIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
